module.exports = {
    url: 'localhost:3000',
    elements: {
        load: 'div[id="pageWrap"]',
        saveBtn: '#saveBtn',
        clear: '#clearBtn',
        results: 'span[name="queryTitle"]',
        hdr: 'input[name="hdrInput"]',
        mke: 'input[name="mkeInput"]',
        oai: 'input[name="oriInput"]',
        nam: 'input[name="namInput"]',
        male: 'select[name="sexInput"] option[value="M"]',
        female: 'select[name="sexInput"] option[value="F"]',
        other: 'select[name="sexInput"] option[value="O"]',
        unknown: 'select[name="sexInput"] option[value="U"]',
        white: 'select[name="racInput"] option[value="W"]',
        black: 'select[name=racInput] option[value="B"]',
        hispanic: 'select[name=racInput] option[value="H"]',
        asian: 'select[name=racInput] option[value="A"]',
        indian: 'select[name=racInput] option[value="I"]',
        unknown: 'select[name=racInput] option[value="U"]',
        hgt: 'input[name="hgtInput"]',
        wgt: 'input[name="wgtInput"]',
        hai: 'input[name="haiInput"]',
        off: 'input[name="offInput"]',
        dow: 'input[name="dowInput"]',
        oln: 'input[name="olnInput"]',
        ols: 'input[name="olsInput"]',
        oly: 'input[name="oldInput"]',
        lic: 'input[name="licInput"]',
        liy: 'input[name="lidInput"]',
        lis: 'input[name="lisInput"]',
        menu: 'div[class="bm-burger-button"]',
        enter: 'p[name="enterOption"]',
        modify: 'p[name="modifyOption"]',
        cancel: 'p[name="cancelOption"]',
        warrant: 'input[name="widInput"]',
        reason: 'input[name="resInput"]',
        date: 'input[name="datInput"]'

    },
}